root: true
env:
  browser: true
  node: true
  es2021: true
extends:
  - eslint:recommended
  - airbnb
  - plugin:node/recommended
  - plugin:react/recommended
  - plugin:import/typescript
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
    impliedStrict: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules:
  no-plusplus: off
  no-use-before-define: warn
  quotes:
    - error
    - double
  prefer-destructuring: off
  no-shadow: warn
  import/extensions: off
  no-restricted-syntax: off
  no-undef: warn
  no-unused-vars: warn
  global-require: warn
  radix: off
  react/prefer-stateless-function: warn
  react/destructuring-assignment: warn
  react/react-in-jsx-scope: off
  react/jsx-filename-extension:
    - 1
    - extensions:
        - .js
        - .jsx
        - .ts
        - .tsx
  class-methods-use-this: warn
  node/no-unsupported-features/es-syntax: off
  node/no-missing-import:
    - error
    - tryExtensions:
        - ".js"
        - ".jsx"
        - ".ts"
        - ".tsx"
  no-process-exit: off
