x-envi: &envi
  PUID: ${PUID}
  PGID: ${PGID}
  TZ: ${TZ}

x-common: &common
  restart: unless-stopped
  networks:
    - fullstack
  environment:
    <<: *envi

services:
  mariadb:
    <<: *common
    container_name: mariadb
    image: lscr.io/linuxserver/mariadb:latest
    ports:
      - 3306:3306
    volumes:
      - ${PWD}/volumes/mariadb/config:/config
      - ${PWD}/volumes/mariadb/data:/var/lib/mysql
    environment:
      <<: *envi
      MYSQL_ROOT_PASSWORD: ${SQL_ROOT_PASSWORD}

  phpmyadmin:
    <<: *common
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 9101:80
    environment:
      <<: *envi
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: ${SQL_ROOT_PASSWORD}

networks:
  fullstack: